### ISSUE TITLE
JavaScript group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Abdulwhbhussain** [Abdulwhbhussain/capstone-module-2#21]
[Link to The GitHub Project - Kanban Board](https://github.com/Abdulwhbhussain/capstone-module-2/projects/1)

Note: There are 2 People in this Project - 1. @Abdulwhbhussain and @Enoisong

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @Abdulwhbhussain and @Enoisong,

✔️ Tasks are properly assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
